ratelimit:
    burst: 30
    enabled: false
    expires: 600000000000
    limit: 10
refresh_interval: 600000000000
server:
    cors:
        allow_origins: null
        cookie_insecure: false
    debug: false
    dev: false
    idle_timeout: 30000000000
    listen: :17610
    openlane:
        token: ""
    read_header_timeout: 2000000000
    read_timeout: 15000000000
    shutdown_grace_period: 10000000000
    tls:
        auto_cert: false
        cert_file: server.crt
        cert_key: server.key
        config: null
        enabled: false
    write_timeout: 15000000000
tracer:
    enabled: false
    environment: development
    otlp:
        certificate: ""
        compression: ""
        endpoint: localhost:4317
        headers: null
        insecure: true
        timeout: 10000000000
    provider: stdout
    stdout:
        disableTimestamp: false
        pretty: true
