version: "3"

env:
  PAT_FILE: pat.env

tasks:
  generate:
    desc: generate a new set of seed data
    cmds:
      - go run cmd/cli/main.go seed generate

  init:
    desc: initialize the new seed data
    dotenv: ['{{.PAT_FILE}}']
    cmds:
      - go run cmd/cli/main.go seed init

  template:
    desc: initialize the new seeded template data
    cmds:
      - go run cmd/cli/main.go seed templates

  seed:
    desc: create a new seeded environment
    cmds:
      - task: generate
      - task: init

  seed:all:
    desc: runs all tasks to create a new seeded environment
    cmds:
      - task: :login
      - task: :org:create
      - task: :token:create
      - export $(awk -F= '{output=output" "$1"="$2} END {print output}' {{.PAT_FILE}})
      - task: seed

  organization:create:
    desc: create a new organization
    cmds:
      - go run cmd/cli/main.go organization create
